name: "Create Promotion PR Action"
description: "Creates a production promotion pull request"
inputs:
  stagingBranch:
    description: "Staging branch name"
    required: true
  prodBranch:
    description: "Production branch name"
    required: true
runs:
  using: "composite"
  steps:
    - if: ${{ github.event.pull_request.merged == true }}
      shell: bash
      run: |
        # Ensure the script is executable
        chmod +x ${{ github.action_path }}/script.sh

        # Execute the script and check for errors
        ${{ github.action_path }}/script.sh ${{ github.repository }} ${{ inputs.stagingBranch }} ${{ inputs.prodBranch }} || echo "Script failed with exit code: $?"
