name: Create Promotion PR Action
description: Creates a production promotion PR
inputs:
  stagingBranch:
    description: Staging branch name
    required: true
  prodBranch:
    description: Production branch name
    required: true
runs:
  using: composite
  steps:
    - if: ${{ github.event.pull_request.merged == true }}
      uses: actions/github-script@v7
      with:
        script: |
          console.log('===============', context)
          const scriptPath = process.env.GITHUB_ACTION_PATH + '/index.js';
          const script = require(scriptPath);
          await script({github, context, core});
