name: Setup Docker
description: Sets up Docker environment for multi-architecture builds
inputs:
  ghcrUsername:
    description: Registry username for Docker login
    default: ${{ github.actor }}
runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcrUsername }}
        password: ${{ env.GITHUB_TOKEN }}

    # Set up for multi-arch builds
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
