name: Continuous integration helper
description: Helper actions for continuous integration
inputs:
  dotenvFile:
    description: Dotenv file
    default: .env.sample
outputs:
  short_sha:
    description: Short SHA of PR head sha or commit sha
  skip_deploy:
    description: Check if the commit message contains (1=skip, 0=deploy)
runs:
  using: node20
  main: dist/index.js
